### ISSUE TITLE
Freebsd not supported, but readme includes it

### ISSUE THREAD

**Issue by Apollon77** [Argonne-National-Laboratory/node-red-contrib-os#11]
We got a report that the node-red module is not installable on freebsd ... but your readme tells also about "os type freebsd" is reported ... which is not really possible then ;-)

Is there a way to also support freebsd?

**Comment by Ekristoffe** [comment]
hello,
Strange is work fine on my PC (inside a Freenas/Truenas jail):
{"hostname":"node-red","type":"FreeBSD","platform":"freebsd","arch":"x64","release":"12.2-RELEASE-p3","endianness":"LE","tmpdir":"/tmp"}

**Comment by Apollon77** [comment]
WHich >2.0.0 you mean? We use 0.2.0 of this nodes. Or do you mean an other library?

**Comment by Ekristoffe** [comment]
Sorry i have messup the version number.
From version 0.2.0 the disk info went from node-df to node-disk-info.
I will see if we can make node-disk-info compatible with freebsd
in between if you can try with the version 0.1.7 it should work on freebsd.

**Comment by Apollon77** [comment]
Thank you for looking into it ... I will workaround for now. Thank you!

**Comment by Ekristoffe** [comment]
hello, i have made a test version of the node-red-contrig-os with BSD support (FreeBSD and OpenBSD)
you can find it here: @ekristoffe/node-red-contrib-os version 0.2.2
if you have free time to test could you please check if it work in your environment ?
thanks

**Comment by Apollon77** [comment]
Can I see the changes somewhere? I asked the affected user  to check

**Comment by Ekristoffe** [comment]
Sure the change are 
https://github.com/cristiammercado/node-disk-info/pull/13
It has been accepted by the original repo. But I have made another change for better compatibility with non UTF8 windows (which I don't think you need it).

**Comment by Apollon77** [comment]
Ok, cool, so we now "Only"  need the official node-red-contrib-os release

**Comment by Ekristoffe** [comment]
Yes I hope by the end of next week all pr would have been merged.

**Comment by Ekristoffe** [comment]
hello i have tested just to install official node-red-contrib-os and it was using the latest node-disk-info (1.2.0).
It should work for your case.
If you need to use it on a non UTF8 windows, node-disk-info PR is not yet merged.

**Comment by Ekristoffe** [comment]
This one could be closed too
