### ISSUE TITLE
Error with German text

### ISSUE THREAD

**Issue by sniicker** [Argonne-National-Laboratory/node-red-contrib-os#12]
Pls correct your Code.

ÜÄÖ are not displayed correctly.

![grafik](https://user-images.githubusercontent.com/67097444/121476293-c2922f80-c9c6-11eb-890e-cd23fc140850.png)

This should show: Wechseldatenträger

Thanks and nice regards

**Comment by Ekristoffe** [comment]
Hello could you please check which version of node-red-contrib-os is installed and also which version of node-disk-info is installed ?
you will need a command access and try those:
npm list -g | grep node-red-contrib-os
npm list -g | grep node-disk-info

or if node-red is only installed locally
npm list | grep node-red-contrib-os
npm list | grep node-disk-info

thanks

**Comment by sniicker** [comment]
Hello, sorry, i was on vacation. 

I checked the versions:
os > 0.2.0
disk > 1.2.0

**Comment by Ekristoffe** [comment]
ok disk is outdated ... 
the problem was solved in >1.3.0 
i will push a new PR for os which force a version of disk > 1.3.0 
please be patient a little more

**Comment by sniicker** [comment]
ok thanks

**Comment by Ekristoffe** [comment]
Ok the update has been accepted in GitHub now we need to wait for npm update then nodered catalog update (the last one I can do it as soon as npm is updated) @jayharper

**Comment by jayharper** [comment]
@Ekristoffe npm has been updated as well as the node red catalog.

**Comment by sniicker** [comment]
Great !! It works now. 

Thank you !
