### ISSUE TITLE
Freemem on Raspi 2

### ISSUE THREAD

**Issue by jschuryk** [Argonne-National-Laboratory/node-red-contrib-os#3]
Can't quite get a handle on what the memory counters are doing.

The memory block is returning:

 { "totalmem": 1004134400, "freemem": 22421504, "memusage": "2.23" }

While free -h from a terminal is showing:

pi@nodered ~ $ free -h
             total       used       free     shared    buffers     cached
Mem:          957M       936M        21M         0B       189M       451M
-/+ buffers/cache:       294M       662M
Swap:          99M         0B        99M

it seems that memusage (being a percent) should really show something around 33% used and 66% free (assuming the free command is returning valid values).  Where is it getting 2.23 from?

The loadavg block is spot on though...

Thanks,

Jerry

**Comment by jayharper** [comment]
There was an issue with calculating the memory usage value.  The code has been updated.  Please test and let me know if this fixes your issue.

**Comment by jschuryk** [comment]
Hi Jay,

The percentages now make more sense - but one further comment.

You seem to be doing the calculations on the memory including the OS buffers and cache.  This means that it will almost always return more than 80% utilized memory, even if you are not doing much.

In the 'free' output above, your memory block would return 21M free.  In reality 662M are free (that is what the second line is describing).

This link describes it in more detail.

http://askubuntu.com/questions/223759/how-to-read-correctly-output-of-free-m-command

I think Windows has a similar concept - I don't have a Node-Red install on windows to compare the output though.

Thanks for the nodes - was doing a bunch of this stuff with OS calls inside a function block - this makes things much cleaner.

Jerry
