### ISSUE TITLE
Drives node crashes node-red

### ISSUE THREAD

**Issue by Hugobox** [Argonne-National-Laboratory/node-red-contrib-os#4]
Here's the output from the console:

11 May 12:04:49 - [red] Uncaught Exception:
11 May 12:04:49 - Error: Command failed: C:\WINDOWS\system32\cmd.exe /s /c "df -kP"
'df' n'est pas reconnu en tant que commande interne
ou externe, un programme ex�cutable ou un fichier de commandes.

```
at ChildProcess.exithandler (child_process.js:203:12)
at emitTwo (events.js:87:13)
at ChildProcess.emit (events.js:172:7)
at maybeClose (internal/child_process.js:818:16)
at Socket.<anonymous> (internal/child_process.js:319:11)
at emitOne (events.js:77:13)
at Socket.emit (events.js:169:7)
at Pipe._onclose (net.js:469:12)
```

**Comment by sbarwe** [comment]
Same here on Windows System(obvious)

**Comment by Lyve1981** [comment]
same here, translation is more or less "df is not recognized as a command". For sure, there is no df under windows.

Ticket is two years old so I expect that this node is no longer maintained?

**Comment by Ekristoffe** [comment]
Hello guys I will see if I can do something about this. Normally i should be able to make it work. I will see if I can contact the original author.

**Comment by jayharper** [comment]
Hi guys, as @Lyve1981 surmised this is not an "active" project on my radar.  It was a simple node I created for use on my Linux based servers.  I did not extensively test on Windows.

**Comment by Ekristoffe** [comment]
Hello I made a pull request which solve this problem.
Hope it will be useful.

**Comment by Ekristoffe** [comment]
@jayharper you may close this issue since the pull #9 solves it.

**Comment by jayharper** [comment]
per @Ekristoffe,  pull #9 solves this issue.
