### ISSUE TITLE
Network Traffic

### ISSUE THREAD

**Issue by rcarmo** [Argonne-National-Laboratory/node-red-contrib-os#8]
Hello, 

I was wondering if:

* The project is still being maintained (it's been 3 years since the last commit)
* There is any plan to add network interface counters (which could be used to monitor network traffic)

Thanks!

**Comment by jayharper** [comment]
Hi,

These nodes are a basic wrapper for the Node.js OS Library, so there really isn't a lot to maintain.  I have no plans to add a network interface counter, but feel free to develop and submit a pull request.
